[project]
name = "shell-lab-extension"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "jupyter-archive==3.5.1",
    "jupyter-server==2.21.0",
    "jupyter-server-terminals==0.5.4",
    "jupyterhub==5.5.1",
]

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["shell_lab_extension"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyter-config/jupyter_server_config.d/shell_lab_extension.json" = "etc/jupyter/jupyter_server_config.d/shell_lab_extension.json"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-jupyter[server]>=0.10.1",
    "ruff>=0.16.10",
]

[tool.mypy]
python_version = "3.14"
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["shell_lab_extension", "shell_lab_extension.*"]
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
extra_checks = true
no_implicit_reexport = true
strict_equality = true
strict_equality_for_none = true
warn_unreachable = true
warn_return_any = true

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["-ra", "--strict-config", "--strict-markers"]
xfail_strict = true

[tool.ruff]
target-version = "py314"
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
preview = true
explicit-preview-rules = true
extend-select = ["fast-api-non-annotated-dependency", "fallible-context-manager", "noqa-comments", "rule-codes-in-selectors"]
ignore = [
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "DOC",
    "line-too-long",
    "EM",
    "FBT",
    "single-line-implicit-string-concatenation",
    "complex-structure",
    "too-many-return-statements",
    "too-many-branches",
    "too-many-arguments",
    "too-many-locals",
    "too-many-statements",
    "magic-value-comparison",
    "too-many-statements-in-try-clause",
    "unnecessary-assign",
    "ambiguous-unicode-character-string",
    "unused-async",
    "TC",
    "raise-vanilla-args",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "ANN",
    "ARG",
    "blocking-path-method-in-async-function",
    "implicit-namespace-package",
    "import-private-name",
    "no-self-use",
    "noqa-comments",
    "assert",
    "private-member-access",
    "print",
    "unused-noqa",
]

[tool.ruff.format]
docstring-code-format = true
