version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: uv
    directories:
      - /hub
      - /lab/extension
    schedule:
      interval: daily
    groups:
      uv-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /hub
      - /lab
      - /web
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
