name: Docker (Lab)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: finki-hub/.github/.github/workflows/docker.yaml@main
    with:
      dockerfile: ./lab/Dockerfile
      context: ./lab
      package-name: shell-lab
      cache-backend: registry
      platforms: linux/amd64
    secrets: inherit
