name: Linters (Web)

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  eslint:
    uses: finki-hub/.github/.github/workflows/eslint.yaml@main
    with:
      working-directory: .
      script: lint
    secrets: inherit

  tsc:
    uses: finki-hub/.github/.github/workflows/tsc.yaml@main
    with:
      working-directory: .
      script: check
    secrets: inherit
